### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
# title: This will be displayed as the website's name in your browser tab.
title: Andrew Larson
# description: This will be meta HTML tag content. This can be ignored.
description: Personal website powered by Jekyll
# baseurl: The subpath of your site
# > set this to "", if you renamed the repository to <user>.github.io
baseurl: ""

# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: Andrew Larson
# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job title, e.g. Fullstack Developer
typing_text: Hobbyiest Software Dev
# profile_picture: This will be the picture shown with your name, size must be noted
profile_picture: https://github.com/Andrew-J-Larson.png?size=192
profile_picture_size: 192px
# email: Your E-Mail address for the email button.
email: contact@Andrew-Larson.dev
# For every social button you want to display, set your username, userid, etc.
# If you do not use one of the following websites, then leave it empty
# > twitter_username:
github_username: Andrew-J-Larson
gitlab_username: Andrew-J-Larson
replit_handle: Andrew-J-Larson
codepen_username: 
dev_username: Andrew-J-Larson
stackoverflow_userid: 7312536
linkedin_username: Andrew-J-Larson
reddit_username: 
x_twitter_username: 
bluesky_handle: # USERNAME.bsky.social
mastodon_userprofile_url: mstdn.social/@Andrew_J_Larson # mastodon verification should work automatically
threads_handle: 
youtube_handle: Andrew-J-Larson
# For every donate button you want to display, set your username, userid, etc.
# If you do not use one of the following websites, then leave it empty
# > kofi_username:
kofi_username: Andrew_J_Larson
patreon_username: Andrew_J_Larson
paypal_username: AndrewJ18Larson
bitcoin_wallet_address: bc1qzmauw4pneakmwjh7yracfrlqqp4n24grgjqs7p

# ABOUT ME SECTION
# show_aboutme_card:
# > setting this to true, will display the About Me section
# > setting this to false, will omit the About Me section
show_aboutme_card: true
# about_me_title: The will be displayed as the title in the About Me section
about_me_title: About Me
# about_me_description: This will be displayed under the title.
about_me_description: At the moment I've achieved Sophomore status in my B.S. in Computer Science at Portland State University (up to course CS 163), but I've been taking a break (since early 2021) mainly due to financial stressors and other personal goals. I have a strong interest in software development/programming, and I am eager to learn and grow in this field. Please reach out to me with any job opportunities related to software developer internships!

# SKILLS SECTION
# show_skills_card:
# > setting this to true, will display the Skills section
# > setting this to false, will omit the Skills section
show_skills_card: true
# about_me_title: The will be displayed as the title in the Skills section
skills_title: Skills

# TIMELINE SECTION
# show_timeline_card:
# > setting this to true, will display the Timeline section
# > setting this to false, will omit the Timeline section
show_timeline_card: true
# timeline_title: The will be displayed as the title in the Timeline section
timeline_title: Education & Experience
# cv_download_link: The link where you host your cv.
# > e.g. you share your cv on your dropbox, then add the dropbox link here
cv_download_link: https://www.linkedin.com/in/Andrew-J-Larson/ # TODO - Once I have enough education/experience for a CV, I'll need to fix this + `.\_includes\section-timeline.html`

# PROJECTS SECTION
# show_projects_card:
# > setting this to true, will display the Projects section
# > setting this to false, will omit the Projects section
show_projects_card: true
# show_projects:
# > setting this to true, will display your listed projects in _data/projects.yml
# > setting this to false, will omit your listed projects
show_projects: true
# projects_title: The will be displayed as the title of your projects
projects_title: Projects
# show_os_projects:
# > setting this to true, will display your public projects on github
# > setting this to false, will omit your public projects on github
show_os_projects: true
# os_projects_title: The will be displayed as the title of your open source projects
os_projects_title: Open Source Projects

# CONTACT SECTION
# show_contact_card:
# > setting this to true, will display the Contact section
# > setting this to false, will omit the Contact section
show_contact_card: true
# contact_title: The will be displayed as the title in the Contact section
contact_title: Contact
# contact_description: This will be displayed under the title.
contact_description: Get in touch with me directly or reply to something on one of my socials!

# DONATE SECTION
# show_donate_card:
# > setting this to true, will display the Donate section
# > setting this to false, will omit the Donate section
show_donate_card: true
# donate_title: The will be displayed as the title in the Donate section
donate_title: Donate
# donate_description: This will be displayed under the title.
donate_description: If you'd like to support me, I accept payments from the following services!

# GITHUB-METADATA
# Set this to your forked repository
# > e.g. <user>/<user>.github.io
repository: Andrew-J-Larson/andrew-j-larson.github.io
projects:
  # sortby:
  # > set this to pushed, if you want to sort your github repositories by time.
  # > set this to stars, if you want to sort your github repositories by stars.
  sort_by: stars
  exclude:
    # archived:
    # > setting this to true, will exclude archived repositories
    # > setting this to false, will also display archived repositories
    archived: true
    # forks:
    # > setting this to true, will exclude forked repositories
    # > setting this to false, will also display forked repositories
    forks: true
    # projects: A list of the repository names you want to exclude from the listing.
    projects:
    # - repo1-to-be-excluded
    # - repo2-to-be-excluded

# GOOGLE-ANALYTICS
# Set the id, if you want to track your website with Google Analytics
# > set this to "", if you do not want to track with Google Analytics
google-analytics:
  id: ""

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
